backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
i18n:
  structure: single_file
  locales: [en, es]
  default_locale: en
collections:
  - name: "pages"
    label: "Páginas Globales"
    i18n:
      structure: single_file
      locales: [en, es]
    files:
      # Index Structure
      - label: "Inicio"
        name: "index"
        file: "src/content/index.md"
        i18n: true
        fields:
          - {label: "Título", name: "slogan", widget: "string", hint: "El título que está por encima del slider", i18n: true, required: false}
          - label: "Slider"
            name: "slider"
            widget: "list"
            summary: "{{fields.title}}"
            i18n: true
            fields:
              - label: "Tipo"
                name: "type"
                widget: "select"
                required: false
                hint: "El tipo de contenido a mostrar en el slider"
                options:
                  - { label: "Imagen", value: "image" }
              - {label: Imagen, name: image, widget: image, hint: Imagen para el slider, required: false}
              - {label: Title, name: title, widget: string, hint: Título de la imagen, required: false}
              - {label: Crédito, name: credit, widget: string, hint: Crédito de la imagen, required: false}
          - {label: Imagen hover para A&D, name: architectsAndDevelopersHover, widget: image, required: false, i18n: duplicate}
          - {label: Imagen hover para B&R, name: brokersAndRealtorsHover, widget: image, required: false, i18n: duplicate}