backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
i18n:
  structure: single_file
  locales: [en, es]
  default_locale: en
collections:
  - name: "pages"
    label: "Páginas Globales"
    i18n:
      structure: single_file
      locales: [en, es]
    files:
      # Globals Structure
      - label: "Información global"
        name: "globals"
        file: "src/content/globals.md"
        i18n: true
        fields:
          - {label: "Texto sección FAQs", name: "faqsText", widget: "text", hint: "El texto para la sección FAQs", i18n: true, required: false}
          - {label: "Texto links FAQs", name: "faqsLinkText", widget: "string", hint: "El texto para el link de la sección FAQs", i18n: true, required: false}
          - {label: "Texto sección Oficinas", name: "officesText", widget: "string", hint: "El texto para la sección Oficinas", i18n: true, required: false}
          - {label: "Imagen sección Oficinas", name: "officesImage", widget: "image", hint: "La imagen para la sección Oficinas", i18n: duplicate, required: false}
          - {label: "Título sección Contacto", name: "contactTitle", widget: "string", hint: "El título para la sección Contacto", i18n: true, required: false}
          - {label: "Texto sección Contacto", name: "contactText", widget: "twxt", hint: "El texto para la sección Contacto", i18n: true, required: false}
      # Index Structure
      - label: "Inicio"
        name: "index"
        file: "src/content/index.md"
        i18n: true
        fields:
          - {label: "Título", name: "slogan", widget: "string", hint: "El título que está por encima del slider", i18n: true, required: false}
          - label: "Slider"
            name: "slider"
            widget: "list"
            summary: "{{fields.title}} – {{ fields.credit}}"
            i18n: true
            fields:
              - label: "Tipo"
                name: "type"
                widget: "select"
                required: false
                hint: "El tipo de contenido a mostrar en el slider"
                options:
                  - { label: "Imagen", value: "image" }
              - {label: Imagen, name: image, widget: image, hint: Imagen para el slider, required: false}
              - {label: Title, name: title, widget: string, hint: Título de la imagen, required: false}
              - {label: Crédito, name: credit, widget: string, hint: Crédito de la imagen, required: false}
          - {label: Imagen hover para A&D, name: architectsAndDevelopersHover, widget: image, required: false, i18n: duplicate}
          - {label: Imagen hover para B&R, name: brokersAndRealtorsHover, widget: image, required: false, i18n: duplicate}
      # Contact Structure
      - label: "Contacto"
        name: "contacto"
        file: "src/content/contact.md"
        i18n: true
        fields:
          - {label: "Título", name: "title", widget: "string", hint: "El título para la barra del navegador", i18n: true, required: false}
          - {label: "Habilitar formulario de contacto?", name: "contactEnabled", widget: "boolean", default: true, i18n: duplicate, required: false}
          - {label: "Habilitar sección FAQs?", name: "faqsEnabled", widget: "boolean", default: true, i18n: duplicate, required: false}
          - {label: "Habilitar mapa?", name: "mapEnabled", widget: "boolean", default: true, i18n: duplicate, required: false}
          - {label: "Habilitar sección Oficinas?", name: "officesEnabled", widget: "boolean", default: true, i18n: duplicate, required: false}